name: GitHub-Profile-Snake-Contrib

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./profile-snake-contrib/github-contribution-grid-snake.svg
            ./profile-snake-contrib/github-contribution-grid-snake-dark.svg?palette=github-dark
            ./profile-snake-contrib/github-contribution-grid-snake.gif
            ./profile-snake-contrib/github-contribution-grid-snake-dark.gif?palette=github-dark

      - name: Push to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Generate Contribution Snake'
          branch: main
